<%
  encoding = 'unicode'
  if ENV.fetch('MORAGA_DB_ADAPTER', nil) == 'mysql2'
    encoding = 'utf8'
  end
%>


default: &default
  adapter: <%= ENV.fetch('MORAGA_DB_ADAPTER', 'postgresql') %>
  encoding: <%= encoding %>
  host: <%= ENV.fetch('MORAGA_DB_HOST', 'database') %>
  port: <%= ENV.fetch('MORAGA_DB_PORT', '5432')  %>
  username: <%= ENV.fetch('MORAGA_DB_USER', 'postgres') %>
  password: <%= ENV.fetch('MORAGA_DB_PASSWORD', 'mysecretpassword') %>
  database: <%= ENV.fetch('MORAGA_DB_NAME', 'postgres') %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: moraga_dev

# Warning: The database defined as "test" will be erased and
# re-generated when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: MORAGA_test

production:
  <<: *default
