# Configuration:
# 
# disabled
#   false if tracking tag should be shown
# use_async
#   Set to true if you want to use asynchronous tracking
# url
#   The url of your piwik instance (e.g. localhost/piwik/
# id_site
#   The id of your website inside Piwik
#

default: &default
  id_site:  <%= ENV['MORAGA_PIWIK_ID'] %>
  url: <%= ENV['MORAGA_PIWIK_URL'] %>
  use_async: <%= ENV.fetch('MORAGA_PIWIK_ASYNC', false) %>
  disabled: <%= ENV.fetch('MORAGA_PIWIK_DISABLED', true) %>
  hostname: <%= ENV.fetch('MORAGA_PIWIK_HOSTNAME', 'localhost') %>

production:
  piwik:
    <<: *default

development:
  piwik:
    <<: *default

test:
  piwik:
    <<: *default
